### ISSUE TITLE
Android Version won't play music through headphones

### ISSUE THREAD

**Issue by Penncilk** [doukutsu-rs/doukutsu-rs#76] opened 2022-03-05 17:03 UTC
When I run the game (I'm using the newest version from GitHub releases), it ignores whatever external audio I have connected, and decides to turn my normal volume down, so when I don't hear anything, I accidentally blast everyone around me with the cave story main theme.

Is there a way I could fix this?

**Comment by dawndus** [comment] 2022-03-05 17:44
Duplicate of #62, tl;dr: it's an upstream issue with the sound library we use and will be fixed when we push a new android build.

**Closed by dawndus** 2022-03-05 17:44 UTC
